name: RGRP
version: 1.3
author: Iggysaur
main: site.modicum.rgrp.RGRP
api-version: 1.7.10

depend: [Towny , SQLiteLib]
website: modicum.site

commands:
  rgrp:
    aliases: railprotect
    usage: /<command> [add|remove|check|getwand|setwand]
    description: Retribution Gaming RailProtect
    permission: rgrp.admin
    permission-message: You do not have permission!

permissions:
  rgrp.admin:
    description: ability to use /rgrp
    default: op